const BEHAVIORAL_SCORING_LABELS = {
  0: "Absent",
  1: "Informal / ad hoc",
  2: "Defined but inconsistent",
  3: "Operationalized / enforced",
};

export const QUESTIONNAIRE = {
  operationalContext: {
    title: "Operational Context",
    description: "Select the option that best matches how your team currently operates.",
    questions: [
      {
        id: "oc_team_size",
        prompt: "How large is the team that builds and maintains the product?",
        options: [
          { score: 1, label: "1-3 people" },
          { score: 2, label: "4-8 people" },
          { score: 3, label: "9-20 people" },
          { score: 4, label: "21+ people or multiple squads" },
        ],
      },
      {
        id: "oc_product_complexity",
        prompt: "How complex is the product surface your team supports?",
        options: [
          { score: 1, label: "Single flow or a few simple screens" },
          { score: 2, label: "Several core flows with moderate variation" },
          { score: 3, label: "Many interconnected flows and roles" },
          { score: 4, label: "Multi-product ecosystem with high variation" },
        ],
      },
      {
        id: "oc_release_frequency",
        prompt: "How often does the team release UI or product changes?",
        options: [
          { score: 1, label: "Monthly or less" },
          { score: 2, label: "Every 2-4 weeks" },
          { score: 3, label: "Weekly" },
          { score: 4, label: "Daily or continuous delivery" },
        ],
      },
      {
        id: "oc_ai_usage",
        prompt: "How much is AI used in product or design/system workflows?",
        options: [
          { score: 1, label: "Little to no AI usage" },
          { score: 2, label: "Occasional AI-assisted tasks by individuals" },
          { score: 3, label: "Regular AI use in multiple team workflows" },
          { score: 4, label: "AI is embedded in core delivery practices" },
        ],
      },
      {
        id: "oc_tooling_fragmentation",
        prompt: "How fragmented are your design and frontend tooling setups?",
        options: [
          { score: 1, label: "Mostly one shared toolchain" },
          { score: 2, label: "A few parallel tools or patterns" },
          { score: 3, label: "Multiple teams using different stacks" },
          { score: 4, label: "Highly fragmented tools with limited alignment" },
        ],
      },
    ],
  },
  structuralMaturity: {
    title: "Structural Maturity",
    description: "Rate each behavior based on what is currently visible in day-to-day delivery.",
    dimensions: [
      "Foundations",
      "Components",
      "Documentation",
      "Governance",
      "Distribution",
      "Adoption",
    ],
    behavioralQuestions: [
      {
        id: "foundations_1",
        dimension: "Foundations",
        prompt: "Design tokens (color, type, spacing) are defined in a shared source.",
        helpText: "Look for a maintained token source used beyond one project.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "foundations_2",
        dimension: "Foundations",
        prompt: "Core tokens are versioned and changes are tracked over time.",
        helpText: "Check whether token changes are visible through changelogs or version history.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "foundations_3",
        dimension: "Foundations",
        prompt: "Themes or brand variants are represented through the same token model.",
        helpText: "Look for explicit support for modes, brands, or platforms without duplicating everything.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "foundations_4",
        dimension: "Foundations",
        prompt: "Token usage is connected to implementation (not only design files).",
        helpText: "Check whether product code references token outputs rather than hard-coded values.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "foundations_5",
        dimension: "Foundations",
        prompt: "Teams can validate whether new UI follows foundational styles.",
        helpText: "Look for linting, checks, or review criteria that catch foundational drift.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "components_1",
        dimension: "Components",
        prompt: "A reusable component library exists for common UI patterns.",
        helpText: "Look for shared components used in more than one feature area.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "components_2",
        dimension: "Components",
        prompt: "Components expose consistent APIs (props, states, variants).",
        helpText: "Check whether similar components follow comparable naming and behavior patterns.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "components_3",
        dimension: "Components",
        prompt: "Accessibility behaviors are built into core components by default.",
        helpText: "Look for keyboard, focus, and semantic patterns implemented at the component level.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "components_4",
        dimension: "Components",
        prompt: "Component quality is validated with automated tests or visual checks.",
        helpText: "Check for repeatable checks that run before release.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "components_5",
        dimension: "Components",
        prompt: "Breaking component changes are managed through clear versioning practices.",
        helpText: "Look for deprecation guidance, migration notes, and release signals.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "documentation_1",
        dimension: "Documentation",
        prompt: "Usage guidance exists for foundational styles and components.",
        helpText: "Check whether teams can find practical guidance without relying on tribal knowledge.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "documentation_2",
        dimension: "Documentation",
        prompt: "Examples show real states and edge cases, not only default views.",
        helpText: "Look for documented loading, error, empty, and disabled states.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "documentation_3",
        dimension: "Documentation",
        prompt: "Docs are updated as part of feature or component changes.",
        helpText: "Check whether updates happen in the same workflow as code/design changes.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "documentation_4",
        dimension: "Documentation",
        prompt: "Contribution guidance explains how to propose and land system changes.",
        helpText: "Look for a clear path to suggest, review, and approve additions or updates.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "documentation_5",
        dimension: "Documentation",
        prompt: "Teams can quickly discover the current recommended pattern for a UI need.",
        helpText: "Check searchability, navigation, and clarity of recommended options.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "governance_1",
        dimension: "Governance",
        prompt: "Roles for maintaining and approving system changes are clearly defined.",
        helpText: "Look for explicit ownership rather than informal handoffs.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "governance_2",
        dimension: "Governance",
        prompt: "There is a consistent intake process for component or token requests.",
        helpText: "Check whether requests follow a visible workflow with triage.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "governance_3",
        dimension: "Governance",
        prompt: "Decision criteria are documented for what enters, changes, or leaves the system.",
        helpText: "Look for transparent standards that teams can reference.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "governance_4",
        dimension: "Governance",
        prompt: "System health is reviewed on a regular cadence.",
        helpText: "Check for recurring reviews of adoption, quality, and backlog priorities.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "governance_5",
        dimension: "Governance",
        prompt: "Exceptions are tracked and revisited with clear expiration or follow-up.",
        helpText: "Look for a visible record of waivers and whether they are resolved over time.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "distribution_1",
        dimension: "Distribution",
        prompt: "Design system assets are delivered through a repeatable release mechanism.",
        helpText: "Check for automated or standardized packaging and publishing steps.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "distribution_2",
        dimension: "Distribution",
        prompt: "Consumers can access versioned packages or artifacts reliably.",
        helpText: "Look for dependable channels such as package registries or pinned releases.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "distribution_3",
        dimension: "Distribution",
        prompt: "Release notes communicate what changed and who is affected.",
        helpText: "Check for change summaries that support planning and upgrades.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "distribution_4",
        dimension: "Distribution",
        prompt: "Migration support is available for teams moving between major versions.",
        helpText: "Look for upgrade guides, codemods, or step-by-step migration help.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "distribution_5",
        dimension: "Distribution",
        prompt: "Release reliability is measurable (failures, rollback, time-to-fix).",
        helpText: "Check whether distribution performance is monitored and improved.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "adoption_1",
        dimension: "Adoption",
        prompt: "Teams actively use shared components for new UI work.",
        helpText: "Look for current projects choosing system components as a default path.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "adoption_2",
        dimension: "Adoption",
        prompt: "Existing products have a visible plan to converge toward shared patterns.",
        helpText: "Check for roadmap items or backlog efforts tied to alignment.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "adoption_3",
        dimension: "Adoption",
        prompt: "Adoption progress is measured with observable indicators.",
        helpText: "Look for metrics such as coverage, usage rates, or exception counts.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "adoption_4",
        dimension: "Adoption",
        prompt: "Teams receive onboarding support for using the system effectively.",
        helpText: "Check for starter guides, office hours, or direct support channels.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
      {
        id: "adoption_5",
        dimension: "Adoption",
        prompt: "Feedback loops from consumers regularly shape system priorities.",
        helpText: "Look for recurring input channels that influence roadmap decisions.",
        scoringLabels: BEHAVIORAL_SCORING_LABELS,
      },
    ],
  },
};
